name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup pnpm
      uses: pnpm/actions-setup@v3
      with:
        version: 8

    - name: Install tailwind dependencies
      run: pnpm install --frozen-lockfile

    - name: Compile css
      run: make build-css

    - name: Build binary
      run: go build -v ./...
